# Generated by Django 5.2.7 on 2025-10-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['goal']},
        ),
        migrations.AddField(
            model_name='campaign',
            name='current_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
