# Generated by Django 5.2.7 on 2025-10-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0002_alter_goal_options_campaign_current_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='indicator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
