# Generated by Django 5.2.7 on 2025-11-05 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_goaltype_goal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='GoalType',
            new_name='CampaignType',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='type',
        ),
        migrations.AddField(
            model_name='campaign',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goal.campaigntype'),
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goal.goalicon'),
        ),
    ]
