# Generated by Django 5.2.7 on 2025-11-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0005_goalicon_rename_goaltype_campaigntype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_target_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
