# Generated by Django 5.2.7 on 2025-11-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0006_campaign_is_target_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_next_goal_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
