# Generated by Django 5.0.7 on 2024-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_name', models.CharField(max_length=100)),
                ('timer_duration', models.IntegerField()),
                ('timer_start', models.DateTimeField(auto_now_add=True)),
                ('timer_end', models.DateTimeField()),
                ('timer_active', models.BooleanField(default=False)),
                ('timer_total_time', models.IntegerField(default=0)),
                ('timer_total_donations', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timer_total_subscriptions', models.IntegerField(default=0)),
                ('timer_total_follows', models.IntegerField(default=0)),
                ('timer_total_raids', models.IntegerField(default=0)),
                ('timer_total_hosts', models.IntegerField(default=0)),
                ('timer_add_time_sub_t1', models.IntegerField(default=0)),
                ('timer_add_time_sub_t2', models.IntegerField(default=0)),
                ('timer_add_time_sub_t3', models.IntegerField(default=0)),
                ('timer_add_time_bits', models.IntegerField(default=0)),
                ('timer_add_time_donation', models.IntegerField(default=0)),
                ('timer_message', models.CharField(default='Timer is currently inactive', max_length=100)),
                ('timer_goal_message', models.CharField(default='Timer goal has not been reached', max_length=100)),
            ],
        ),
    ]
