# Generated by Django 5.0.8 on 2024-08-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BonusTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_condition', models.CharField(choices=[('SUB', 'Sub'), ('FOLLOW', 'Follow'), ('DONATION', 'Donation'), ('BITS', 'Bits')], max_length=10)),
                ('bonus_value', models.IntegerField()),
                ('bonus_time', models.IntegerField()),
                ('bonus_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_name', models.CharField(max_length=100)),
                ('timer_initial_time', models.IntegerField()),
                ('timer_start', models.DateTimeField()),
                ('timer_end', models.DateTimeField()),
                ('timer_active', models.BooleanField(default=False)),
                ('timer_total_donations', models.FloatField(default=0)),
                ('timer_total_subscriptions', models.IntegerField(default=0)),
                ('timer_total_follows', models.IntegerField(default=0)),
                ('timer_total_bits', models.IntegerField(default=0)),
                ('timer_add_time_sub_t1', models.IntegerField(default=0)),
                ('timer_add_time_sub_t2', models.IntegerField(default=0)),
                ('timer_add_time_sub_t3', models.IntegerField(default=0)),
                ('timer_add_time_bits', models.FloatField(default=0)),
                ('timer_add_time_donation', models.FloatField(default=0)),
                ('timer_message', models.CharField(default='Timer is currently inactive', max_length=100)),
                ('timer_goal_message', models.CharField(default='Timer goal has not been reached', max_length=100)),
                ('bonus_times', models.ManyToManyField(blank=True, to='subathonTimer.bonustime')),
            ],
        ),
    ]
