# Generated by Django 5.0.8 on 2024-09-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=100)),
                ('goal_amount', models.FloatField()),
                ('goal_image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
