# Generated by Django 5.0.7 on 2024-07-18 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='timer_duration',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='timer_start',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='timer_total_time',
        ),
    ]
