# Generated by Django 5.0.7 on 2024-08-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0002_timer_bonus_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='bonus_time',
        ),
        migrations.AddField(
            model_name='timer',
            name='bonus_times',
            field=models.ManyToManyField(blank=True, to='subathonTimer.bonustime'),
        ),
    ]
