# Generated by Django 5.0.7 on 2024-08-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0003_remove_timer_bonus_time_timer_bonus_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='timer_total_bits',
            field=models.IntegerField(default=0),
        ),
    ]
