# Generated by Django 5.0.7 on 2024-08-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0004_timer_timer_total_bits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='timer_total_bits',
            field=models.FloatField(default=0),
        ),
    ]
