# Generated by Django 5.0.8 on 2024-09-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0004_alter_tipgoal_goal_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=100)),
                ('goal_amount', models.FloatField()),
                ('goal_image', models.ImageField(upload_to='subathonTimerEphemeriia/static/subathonTimer/images/subs/')),
            ],
        ),
    ]
