# Generated by Django 5.0.7 on 2024-08-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0005_alter_timer_timer_total_bits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='timer_add_time_bits',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_add_time_donation',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_total_bits',
            field=models.IntegerField(default=0),
        ),
    ]
