# Generated by Django 5.0.7 on 2024-08-07 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0006_alter_timer_timer_add_time_bits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='timer_total_donations',
            field=models.FloatField(default=0),
        ),
    ]
