# Generated by Django 5.0.8 on 2024-09-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0006_alter_timer_timer_end_alter_timer_timer_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='paused_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timer',
            name='timer_paused',
            field=models.BooleanField(default=False),
        ),
    ]
