# Generated by Django 5.1.5 on 2025-02-08 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0007_timer_paused_time_timer_timer_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgoal',
            name='timer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subathonTimer.timer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipgoal',
            name='timer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subathonTimer.timer'),
            preserve_default=False,
        ),
    ]
