# Generated by Django 5.1.6 on 2025-02-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0008_subgoal_timer_tipgoal_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipgoal',
            name='goal_image_validated',
            field=models.ImageField(default=models.ImageField(upload_to='subathonTimerEphemeriia/static/subathonTimer/images/tips/'), upload_to='subathonTimerEphemeriia/static/subathonTimer/images/tips/validated/'),
        ),
    ]
