# Generated by Django 5.1.6 on 2025-02-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0009_tipgoal_goal_image_validated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipgoal',
            name='goal_image_validated',
            field=models.ImageField(blank=True, null=True, upload_to='subathonTimerEphemeriia/static/subathonTimer/images/tips/validated/'),
        ),
    ]
