# Generated by Django 5.1.6 on 2025-03-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0011_subgoal_goal_image_validated'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='multiplicator_on',
            field=models.BooleanField(default=True),
        ),
    ]
