# Generated by Django 5.1.10 on 2025-08-01 22:24

import subathonTimerEphemeriia.storage_backends
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0012_timer_multiplicator_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgoal',
            name='goal_image',
            field=models.ImageField(storage=subathonTimerEphemeriia.storage_backends.GoalStorage(), upload_to=utils.utils.rename_file_to_upload),
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='goal_image_validated',
            field=models.ImageField(blank=True, null=True, storage=subathonTimerEphemeriia.storage_backends.GoalStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='tipgoal',
            name='goal_image',
            field=models.ImageField(storage=subathonTimerEphemeriia.storage_backends.GoalStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='tipgoal',
            name='goal_image_validated',
            field=models.ImageField(blank=True, null=True, storage=subathonTimerEphemeriia.storage_backends.GoalStorage(), upload_to=''),
        ),
    ]
