# Generated by Django 5.1.10 on 2025-08-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0013_alter_subgoal_goal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='timer_nb_subs',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='timer',
            name='timer_nb_tips',
            field=models.IntegerField(default=3),
        ),
    ]
