# Generated by Django 5.1.10 on 2025-08-02 17:12

import django.db.models.deletion
import subathonTimerEphemeriia.storage_backends
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0014_timer_timer_nb_subs_timer_timer_nb_tips'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(storage=subathonTimerEphemeriia.storage_backends.AnnouncementStorage(), upload_to=utils.utils.rename_file_to_upload)),
                ('duration', models.IntegerField(default=10, help_text='Duration in seconds for the announcement to be displayed')),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='subathonTimer.timer')),
            ],
        ),
    ]
