# Generated by Django 5.1.10 on 2025-08-03 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0015_carouselannouncement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timer',
            old_name='multiplicator_on',
            new_name='multiplicator_sub_on',
        ),
    ]
