# Generated by Django 5.1.10 on 2025-08-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0015_carouselannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='nb_seconds_announcement',
            field=models.IntegerField(default=300, help_text='Number of seconds between each announcement will be displayed'),
        ),
    ]
