# Generated by Django 5.1.10 on 2025-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0016_rename_multiplicator_on_timer_multiplicator_sub_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='multiplicator_tip_on',
            field=models.BooleanField(default=True),
        ),
    ]
