# Generated by Django 5.1.10 on 2025-08-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0016_timer_nb_seconds_announcement'),
        ('subathonTimer', '0017_timer_multiplicator_tip_on'),
    ]

    operations = [
    ]
