# Generated by Django 6.0 on 2025-12-11 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0018_merge_20250803_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgoal',
            name='goal_image',
        ),
        migrations.RemoveField(
            model_name='subgoal',
            name='goal_image_validated',
        ),
    ]
