# Generated by Django 6.0 on 2025-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0019_remove_subgoal_goal_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipgoal',
            name='goal_image',
        ),
        migrations.RemoveField(
            model_name='tipgoal',
            name='goal_image_validated',
        ),
        migrations.AlterField(
            model_name='subgoal',
            name='goal_amount',
            field=models.SmallIntegerField(),
        ),
    ]
