# Generated by Django 6.0.5 on 2026-05-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0020_remove_tipgoal_goal_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='timer_total_both',
            field=models.FloatField(default=0),
        ),
    ]
