# Generated by Django 6.0.5 on 2026-05-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subathonTimer', '0021_timer_timer_total_both'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipgoal',
            name='goal_type',
            field=models.CharField(choices=[('GIVEAWAY', 'Giveaway'), ('GAMING', 'Gaming'), ('MISC', 'Misc')], default='MISC', max_length=10),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_add_time_bits',
            field=models.FloatField(default=0, help_text='Time in seconds added for each bit'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_add_time_donation',
            field=models.FloatField(default=0, help_text='Time in seconds added for each currency unit donated'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_add_time_sub_t1',
            field=models.IntegerField(default=0, help_text='Time in seconds added for a tier 1 subscription'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_add_time_sub_t2',
            field=models.IntegerField(default=0, help_text='Time in seconds added for a tier 2 subscription'),
        ),
        migrations.AlterField(
            model_name='timer',
            name='timer_add_time_sub_t3',
            field=models.IntegerField(default=0, help_text='Time in seconds added for a tier 3 subscription'),
        ),
    ]
