# Generated by Django 5.1.1 on 2024-10-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_twitch',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bingo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
