# Generated by Django 5.1.1 on 2024-10-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0002_user_id_twitch_alter_bingo_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
