# Generated by Django 5.1.1 on 2024-10-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingo', '0003_alter_bingo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_won',
            field=models.BooleanField(default=False),
        ),
    ]
