# Generated by Django 5.1.5 on 2025-01-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='twitch_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
