# Generated by Django 5.0.7 on 2024-08-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchauth',
            name='expires_in',
            field=models.IntegerField(),
        ),
    ]
