# Generated by Django 5.0.7 on 2024-08-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_twitchauth_expires_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamlabsauth',
            name='expires_in',
            field=models.IntegerField(),
        ),
    ]
