# Generated by Django 5.0.7 on 2024-08-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_alter_streamlabsauth_expires_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamlabsauth',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamlabsauth',
            name='scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
