# Generated by Django 5.1.5 on 2025-01-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_alter_streamlabsauth_refresh_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=2083)),
                ('refresh_token', models.CharField(max_length=2083)),
                ('expires_in', models.IntegerField()),
                ('token_type', models.CharField(max_length=255)),
                ('scope', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
