# Generated by Django 5.0.7 on 2024-08-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0005_alter_streamlabsauth_expires_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamlabsauth',
            name='socket_token',
            field=models.CharField(default='re', max_length=255),
            preserve_default=False,
        ),
    ]
