# Generated by Django 5.1.5 on 2025-01-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0006_chatbotauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotauth',
            name='bot_name',
            field=models.CharField(default='Chatbot', max_length=255),
        ),
    ]
