# Generated by Django 5.1.5 on 2025-01-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0007_chatbotauth_bot_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotauth',
            name='bot_name',
            field=models.CharField(max_length=255),
        ),
    ]
