# Generated by Django 5.1.6 on 2025-04-17 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_opened', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('size', models.IntegerField()),
                ('image_url', models.URLField()),
                ('coordonates', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('mask_url', models.URLField()),
                ('background_url', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
                ('cells', models.ManyToManyField(related_name='cells', to='giveaway.calendarcell')),
            ],
        ),
        migrations.AddField(
            model_name='calendarcell',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_cells', to='giveaway.cell'),
        ),
        migrations.AddField(
            model_name='calendarcell',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giveaway.reward'),
        ),
    ]
