# Generated by Django 5.1.6 on 2025-03-14 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('background_url', models.URLField()),
                ('cells', models.ManyToManyField(related_name='cells', to='giveaway.cell')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='reward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giveaway.reward'),
        ),
    ]
