# Generated by Django 5.1.6 on 2025-04-19 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('mask_url', models.URLField()),
                ('background_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='background_url',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='mask_url',
        ),
        migrations.RemoveField(
            model_name='calendar',
            name='size',
        ),
        migrations.AddField(
            model_name='calendar',
            name='base_calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='giveaway.basecalendar'),
            preserve_default=False,
        ),
    ]
