# Generated by Django 5.1.6 on 2025-04-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0002_basecalendar_remove_calendar_background_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecalendar',
            name='background_url',
        ),
        migrations.AddField(
            model_name='calendar',
            name='background_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
