# Generated by Django 5.1.6 on 2025-03-15 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0003_alter_cell_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='giveaway.reward'),
        ),
    ]
