# Generated by Django 5.1.6 on 2025-04-20 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0003_remove_basecalendar_background_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='cells',
        ),
        migrations.AddField(
            model_name='calendarcell',
            name='calendar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='giveaway.calendar'),
            preserve_default=False,
        ),
    ]
