# Generated by Django 5.1.6 on 2025-03-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0004_alter_cell_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
