# Generated by Django 5.1.6 on 2025-04-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0004_remove_calendar_cells_calendarcell_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
