# Generated by Django 5.1.6 on 2025-04-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0005_alter_reward_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='reward_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='reward_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='reward_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='reward_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
