# Generated by Django 5.1.6 on 2025-03-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0005_calendar_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='coord_x',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='coord_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cell',
            name='radius',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
