# Generated by Django 5.1.6 on 2025-03-17 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0006_cell_coord_x_cell_coord_y_cell_radius'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='coord_x',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='coord_y',
        ),
        migrations.RemoveField(
            model_name='cell',
            name='radius',
        ),
        migrations.AddField(
            model_name='cell',
            name='coordonates',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
