# Generated by Django 5.1.9 on 2025-05-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0006_cell_reward_height_cell_reward_width_cell_reward_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
