# Generated by Django 5.1.6 on 2025-03-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0007_remove_cell_coord_x_remove_cell_coord_y_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='coordonates',
            field=models.CharField(max_length=500),
        ),
    ]
