# Generated by Django 5.1.9 on 2025-05-22 20:59

import subathonTimerEphemeriia.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0008_alter_reward_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.FileField(blank=True, null=True, storage=subathonTimerEphemeriia.storage_backends.RewardStorage(), upload_to=''),
        ),
    ]
