# Generated by Django 5.1.6 on 2025-04-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0008_alter_cell_coordonates'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
