# Generated by Django 5.1.9 on 2025-05-22 21:02

import subathonTimerEphemeriia.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0009_alter_reward_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=subathonTimerEphemeriia.storage_backends.RewardStorage(), upload_to=''),
        ),
    ]
