# Generated by Django 5.1.9 on 2025-05-22 21:31

import subathonTimerEphemeriia.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0011_alter_calendarcell_reward'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='background_url',
        ),
        migrations.AddField(
            model_name='calendar',
            name='background',
            field=models.ImageField(blank=True, null=True, storage=subathonTimerEphemeriia.storage_backends.BackgroundStorage(), upload_to=''),
        ),
    ]
