# Generated by Django 5.1.9 on 2025-05-23 16:58

import subathonTimerEphemeriia.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0012_remove_calendar_background_url_calendar_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='background',
            field=models.ImageField(default='default/FONDSCENEVIERGE.jpg', storage=subathonTimerEphemeriia.storage_backends.BackgroundStorage(), upload_to=''),
        ),
    ]
