# Generated by Django 5.1.9 on 2025-05-23 17:23

import giveaway.models
import subathonTimerEphemeriia.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0014_alter_calendar_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=subathonTimerEphemeriia.storage_backends.RewardStorage(), upload_to=giveaway.models.rename_file_to_upload),
        ),
    ]
