# Generated by Django 5.1.10 on 2025-08-01 22:24

import subathonTimerEphemeriia.storage_backends
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaway', '0015_alter_reward_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='background',
            field=models.ImageField(default='FONDSCENEVIERGE.jpg', storage=subathonTimerEphemeriia.storage_backends.BackgroundStorage(), upload_to=utils.utils.rename_file_to_upload),
        ),
    ]
