# Generated by Django 5.1.10 on 2025-08-06 10:05

import django.db.models.deletion
import subathonTimerEphemeriia.storage_backends
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Whell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('number', models.IntegerField(default=1)),
                ('image', models.ImageField(blank=True, null=True, storage=subathonTimerEphemeriia.storage_backends.RewardStorage(), upload_to=utils.utils.rename_file_to_upload)),
                ('whell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='wheel.whell')),
            ],
            options={
                'unique_together': {('whell', 'text')},
            },
        ),
    ]
