# Generated by Django 5.1.10 on 2025-08-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whell',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
